table Athlete
	lineageTag: 44b82ce8-0fe6-537b-b9ce-c5894ae8007c

	measure 'Weeks Post-Op (Auto)' =
			
			VAR SurgeryDate = MAX('Athlete'[Surgery Date])
			VAR AsOf = [As Of Date]
			RETURN
			IF(ISBLANK(SurgeryDate) || ISBLANK(AsOf), BLANK(), DATEDIFF(SurgeryDate, AsOf, WEEK))
		formatString: 0
		lineageTag: 3f4df65d-eeb8-5379-b974-b49ec557fa94

	measure 'KF Prone Status' =
			
			VAR Threshold = CALCULATE(MAX('Criteria'[Threshold]), 'Criteria'[Metric Name] = "KF Prone Asym %", 'Criteria'[Phase ID] = MAX('Criteria'[Phase ID]))
			VAR CurrentValue = [Latest KF Prone Asym %]
			RETURN
			IF(ISBLANK(CurrentValue), "—", IF(CurrentValue <= Threshold, "✓", "✗"))
		lineageTag: 327bb774-07d0-4785-a0cb-fb399e511fb9

	column Name
		dataType: string
		lineageTag: 2e5435e9-f357-5f78-b791-1331f098889b
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column 'Injury Type'
		dataType: string
		lineageTag: 63bcd720-1b4f-58f4-8ad9-1099acd705ac
		summarizeBy: none
		sourceColumn: Injury Type

		annotation SummarizationSetBy = Automatic

	column 'Surgery Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 7203f17e-e3e8-5997-9168-01c2935ad181
		summarizeBy: none
		sourceColumn: Surgery Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Operated Limb'
		dataType: string
		lineageTag: 676464c1-ee2a-5c0b-bb34-558573c01869
		summarizeBy: none
		sourceColumn: Operated Limb

		annotation SummarizationSetBy = Automatic

	column 'Current Phase ID'
		dataType: string
		lineageTag: 5abf405b-d0bf-5ebe-bfa2-31bcd2f9fa02
		summarizeBy: none
		sourceColumn: Current Phase ID

		annotation SummarizationSetBy = Automatic

	column 'Photo URL'
		dataType: string
		lineageTag: 5fc6b3bb-3cfa-52e8-8fd7-95746c5d2e09
		summarizeBy: none
		sourceColumn: Photo URL

		annotation SummarizationSetBy = Automatic

	partition Athlete = m
		mode: import
		source =
				// Athlete roster: surgery date, operated limb, current phase and an optional photo URL. The phase is set by hand
				// (athletes can be ahead of or behind the calendar). Athletes found in the exports but missing
				// from the roster still appear, with blank surgery details.
				let
				    Spec = {
				        {"Name", {"Name", "Athlete", "Athlete Name"}, "text"},
				        {"ExternalId", {"ExternalId", "External Id"}, "text"},
				        {"Injury Type", {"Injury Type", "Injury"}, "text"},
				        {"Surgery Date", {"Surgery Date", "Date of Surgery"}, "date"},
				        {"Operated Limb", {"Operated Limb", "Limb", "Side"}, "text"},
				        {"Current Phase ID", {"Current Phase ID", "Phase ID", "Phase"}, "text"},
				        {"Photo URL", {"Photo URL", "Photo", "Headshot", "Image URL"}, "text"}
				    },
				    Roster = Fx[Shape](Athletes[RosterRaw], Spec),
				    Limb = (v) => if v = null then null else let t = Text.Upper(Text.Start(Text.Trim(v), 1)) in if t = "L" then "Left" else if t = "R" then "Right" else null,
				    Rows = Table.FromRecords(Table.TransformRows(Roster, (r) => r & [
				        Name = Athletes[Display](Athletes[Resolve](r[Name], r[ExternalId])),
				        #"Operated Limb" = Limb(r[#"Operated Limb"]),
				        #"Injury Type" = if r[#"Injury Type"] = null then "ACL" else r[#"Injury Type"],
				        #"Current Phase ID" = if r[#"Current Phase ID"] = null then "1" else Text.From(r[#"Current Phase ID"])]),
				        Table.ColumnNames(Roster) & {}, MissingField.UseNull),
				    FromRoster = Table.SelectRows(Table.RemoveColumns(Rows, {"ExternalId"}), each [Name] <> null),
				    InData = List.Transform(Athletes[Names], Athletes[Display]),          // everyone in any export
				    Missing = List.Difference(InData, FromRoster[Name]),
				    Extra = Table.FromRecords(List.Transform(Missing, each [Name = _, #"Injury Type" = "ACL", #"Surgery Date" = null, #"Operated Limb" = null, #"Current Phase ID" = "1", #"Photo URL" = null])),
				    All = Table.Distinct(Table.Combine({FromRoster, Extra}), {"Name"}),
				    Typed = Table.TransformColumnTypes(All, {{"Name", type text}, {"Injury Type", type text}, {"Surgery Date", type date}, {"Operated Limb", type text}, {"Current Phase ID", type text}, {"Photo URL", type text}})
				in
				    Typed

	annotation PBI_ResultType = Table

